apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadogkg4130-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadogkg4130-tenant-component
    app.kubernetes.io/part-of: loadogkg4130-tenant-app
  name: loadogkg4130-tenant-component
  namespace: loadogkg4130-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadogkg4130-tenant-component
    weight: null
status: {}
